apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: "https://github.com/freeman9917/argocd.git"
    path: "dev/applications"
    targetRevision: "HEAD"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
