config:
  registries:
    - name: ECR
      api_url: "https://013273876354.dkr.ecr.eu-central-1.amazonaws.com"
      prefix: 013273876354.dkr.ecr.eu-central-1.amazonaws.com
      default: true
      ping: yes
      insecure: no
      credentials: ext:/scripts/ecr-login.sh #script name should match here and in authScripts
      credsexpire: 11h
authScripts:
  enabled: true
  scripts:
    ecr-login.sh: | # notice script name matches above
      #!/bin/sh
      aws ecr --region "eu-central-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
